language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BKjnHlfFBAArikqXStceLfDQD4P+zSer83O9fumSplDQNVIz6qJoDn1tlVQQ1+OcQKYbtiLtsHnTx1Ml5I6TthLwJKhnB2N6SQurDe25BH5cnmS4oU7rMoLj0ohZjixNdrxsH5s7B4EVWv2DK4cVm+4WXocVW7PWeLETVvd7a4k=
  file:
    - "nlcst-test.js"
    - "nlcst-test.min.js"
  on:
    tags: true
    node: '9.0'
